---
default: true
whitespace: false

# MD001 - Heading levels should only increment by one level at a time
heading-increment: false

# MD003 - Heading style
heading-style:
    style: atx

# MD004 - Unordered list style - Tags: bullet, ul
ul-style:
    style: dash

# MD005 - Inconsistent indentation for list items at the same level
list-indent: true

# MD007 - Unordered list indentation
ul-indent:
   indent: 4

# 2 is the default. However, various linters and prettiers absolutely require 4. We should not run into this often. If we do, we can look at this.

# MD009 - Trailing spaces. See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009---trailing-spaces
no-trailing-spaces:
    br_spaces: 2
    list_item_empty_lines: true

# MD010 - Hard tabs
no-hard-tabs: 
    spaces_per_tab: 1
    code_blocks: true
    ignore_code_languages:

# MD011 - Reversed link syntax
    no-reversed-links: true


# MD012 - Multiple consecutive blank lines
no-multiple-blanks: false

# Sigrunixia Recommends Disabling this as blank lines do matter in Obsidian rendering due to some themes turning them into <br />
# Default maximum is 1

# MD013 - Line length
line-length: 1000
code_blocks: false
headers: true
heading_line_length: 200
stern: true
tables: false

 # MD014 - Dollar signs used before commands without showing output
commands-show-output: false

 # MD018 - No space after hash on atx style heading
no-missing-space-atx: false



# MD019 - Multiple spaces after hash on atx style heading
no-multiple-space-atx: true

# Sigrunixia recommends this be set to true. This fixes headings that should be headings.
# #  Header that has too much space
# # Header that is the right space

# MD020 - No space inside hashes on closed atx style heading
no-missing-space-closed-atx: false

# Sigrunixia recommends that set this to false.
# Sadly, this rule will also fire if either side of the "header" is missing a space, acting the same as MD018.

# MD021 - Multiple spaces inside hashes on closed atx style heading
no-multiple-space-closed-atx: false

 # Sigrunixia recommends this be set to false.
 # I cannot trust it to not overreach on tags

 # MD022 - Headings should be surrounded by blank lines
lanks-around-headings: false
 #  lines_above: 2
 #  lines_below: 1

 # Sigrunixia recommends this as false due to infoboxes and callouts

 # MD023 - Headings must start at the beginning of the line
heading-start-left: false

# Sigrunixia recommends this as false due to infoboxes and callouts

# MD024 - Multiple headings with the same content
no-duplicate-heading:
   allow_different_nesting: true

# For outline purposes and linking, duplicate headings suck. We have options here:
# Different nesting is Main -> Boo -> Bah and Main -> Lah -> Bah is okay
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md024---multiple-headings-with-the-same-content and lets talk.

# MD025 - Multiple top level headings in the same document
single-h1: false
# front_matter_title: "" This is used if YAML has a title key
# level: 1 Default header level is 1. This can be set to 2 for Obsidian. Github will kill us.

# Sigrunixia prefers true, but she knows Josh and Co have H1 like 3 times.
# So this is likely going to be false.

# MD026 - Trailing punctuation in heading
no-trailing-punctuation: true
#  punctuation: (string, default .,;:!。，；：！)

# Sigrunixia recommends true as some headings, themes, and plugins will not render things like .,;:!。，；：!.
# We can choose what to ignore, however.

# MD027 - Multiple spaces after blockquote symbol
no-multiple-space-blockquote: true

# Sigrunixia recommends true as this can break callout formatting for things like columns and infoboxes.
# Example is >> [NestedInfobox] is okay.
# However >>  is not because it will not conform to the same nested level.
# This will also trigger indendtation rules.

# MD028 - Blank line inside blockquote
no-blanks-blockquote: false

# Sigrunixia recommends false as this can break callout formatting for things like columns and infoboxes.
# Oftentime callouts of different sorts are separated only by one blank line.

# MD029 - Ordered list item prefix
ol-prefix:
    style: ordered


# Sigrunixia recommends ordered.
# There is little reason to have a numbered list using the same number.
# 1. Pie versus 1. Pie
# 1. Pie versus 2. Pie
# 1. Pie versus 3. Pie

# MD030 - Spaces after list markers
list-marker-space:
    ul_single: 3
    ol_single: 1
    ul_multi: 3
    ol_multi: 1

# Sigrunixia recommends this as true.
# Default for everything is 1. However, parsers and linters typically require UL to be 3 spaces.

# MD031 - Fenced code blocks should be surrounded by blank lines
blanks-around-fences: true
list_items: false

# Sigrunixia recommends this as true.
# Some parsers and editors will not read without a blank line before and after.
# Also recommends disabling for list items.

# MD032 - Lists should be surrounded by blank lines
blanks-around-lists: false

# As above, recommend disabling for lists.

# MD033 - Inline HTML
no-inline-html: false

# Sigrunixia recommends leaving as false.

# MD034 - Bare URL used
no-bare-urls: true

# Sigrunixia recommends true to turn bare links into a markdown compatible clickable link.

# MD035 - Horizontal rule style
hr-style:
    style: "* * *"

# Sigrunixia recommends Style * * * to prevent --- creating headers.
# Nor accidently turning strong and emphasis into a line.

# MD036 - Emphasis used instead of a heading
no-emphasis-as-heading: false
#  punctuation: (string, default .,;:!?。，；：！？)

# Sigrunixia recommends leaving false
# Sometimes bold is better than a header

# MD037 - Spaces inside emphasis markers
no-space-in-emphasis: true

# Sirgunixia recommends leaving this true to fix spaces between words and their emphasis.
# ** Word ** becomes **Word**
# If someone intentionally wanted ** Word **, they can use graves or backslash.

# MD038 - Spaces inside code span elements
no-space-in-code: true

# Sigrunixia recommends leaving this true.
# Fixes this `` `backticks` ``

# MD039 - Spaces inside link text
no-space-in-links: true

# Sigrunixia recommends leaving this true.
# Fixes [ a link ](https://www.example.com/)

# MD040 - Fenced code blocks should have a language specified
fenced-code-language: true

# Sigrunixia recommends leaving this true.
# It only wants to see ```statblock
# It does not want to see ``` ... bueller?

# MD041 - First line in file should be a top level heading
first-line-h1: false

# Sigrunixia recommends leaving this false
# For YAML.

# MD042 - No empty links
no-empty-links: true

# Sigrunixia recommends leaving this true
# No reason for empty links.

# MD043 - Required heading structure
required-headings: true

# Sigrunixia recommends leaving this false
# We're not forcing header levels.
# Same for Structure


# MD044 - Proper names should have the correct capitalization
proper-names:
   names:
     - JavaScript
   html_elements: true
   code_blocks: true

# Sigrunixia is curious about leaving this as true.
# It may cut the need for a different linter file.


# MD045 - Images should have alternate text (alt text)
no-alt-text: true

# Sigrunixia suggests leaving this as true
# For accessability reasons.

# MD046 - Code block style
code-block-style:
    style: fenced

# Sigrunixia suggests leaving this as true

# MD047 - Files should end with a single newline character
single-trailing-newline: true

# MD048 - Code fence style
code-fence-style:
    style: backtick


# MD049 - Emphasis style should be consistent
emphasis-style:
    style: asterisk

# MD050 - Strong style should be consistent
strong-style:
    style: asterisk

# Sigrunixia has a question
# She was unable to test this adequately with statblocks in the linter.
# Theoretically, MD linter should leave codeblock alone for strong
# If it does not, we want underscore, or else statblock bold will stop working.
# Help please?

# MD051 - Link fragments should be valid
link-fragments: true

# Sigrunixia recommends leaving this as true.
# It helps keep Github Consistency
# Changes # Title [Link](#fragment) to # Title [Link](#title)

# MD052 - Reference links and images should use a label that is defined
reference-links-images: true


# MD053 - Link and image reference definitions should be needed
link-image-reference-definitions: true
